# Generated by Django 4.1.7 on 2023-03-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_profile_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='certification',
        ),
    ]
