# Generated by Django 4.1.7 on 2023-03-23 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_program_instructor_registeredstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
    ]
