# Generated by Django 4.1.7 on 2023-03-23 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cat_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.category'),
        ),
    ]
