# Generated by Django 4.1.7 on 2023-03-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_program_cat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='cat_name',
        ),
    ]
