# Generated by Django 4.1.7 on 2023-03-20 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_profile_gender_alter_profile_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='instructor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
